/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norootfw_NoRootFwNative */

#ifndef _Included_com_norootfw_NoRootFwNative
#define _Included_com_norootfw_NoRootFwNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norootfw_NoRootFwNative
 * Method:    ip_input
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_norootfw_NoRootFwNative_ip_1input
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
