/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norootfw_NoRootFwNative */

#ifndef _Included_com_norootfw_NoRootFwNative
#define _Included_com_norootfw_NoRootFwNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norootfw_NoRootFwNative
 * Method:    sendSyn
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_norootfw_NoRootFwNative_sendSyn
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_norootfw_NoRootFwNative
 * Method:    sendUdpRequest
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_norootfw_NoRootFwNative_sendUdpRequest
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_norootfw_NoRootFwNative
 * Method:    initTun0NetIf
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_norootfw_NoRootFwNative_initTun0NetIf
  (JNIEnv *, jclass);

/*
 * Class:     com_norootfw_NoRootFwNative
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_norootfw_NoRootFwNative_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
